openapi: 3.1.0
info:
  title: PuppyLove2.0_Backend
  description: API Documentation for PuppyLove2.0_Backend [Github](https://github.com/pclubiitk/puppylove2.0_backend)
  version: 1.0.0
  contact:
    url: https://pclub.in/
  x-logo:
    url: https://pclub.in/images/pclub.png

tags:
  - name: Session
    description: Endpoints for Session Login and Logout.
  - name: User
    description: Endpoints for Users.
  - name: Admin
    description: Endpoints for Admin Use.
  - name: Fetch
    description: Endpoints for Fetching Tabular Data Fields for all users.
  - name: Send
    description: Endpoints for user to insert data in DB.
  - name: Verify
    description: Enpoints for user to verify claims about data in DB.
paths:
  /users/mail:id:
    $ref: paths/users/mail:id.yaml
  /users/login/first:
    $ref: paths/users/login/first.yaml
  /session/login:
    $ref: paths/session/login.yaml
  /session/logout:
    $ref: paths/session/logout.yaml
  /session/admin/login:
    $ref: paths/session/admin/login.yaml
  /admin/user/deleteallusers:
    $ref: paths/admin/user/deleteallusers.yaml
  /admin/user/new:
    $ref: paths/admin/user/new.yaml
  /admin/user/delete:
    $ref: paths/admin/user/delete.yaml
  /admin/publish:
    $ref: paths/admin/publish.yaml
  /users/activeusers:
    $ref: paths/users/activeusers.yaml
  /users/fetchPublicKeys:
    $ref: paths/users/fetchPublicKeys.yaml
  /users/fetchall:
    $ref: paths/users/fetchall.yaml
  /users/fetchReturnHearts:
    $ref: paths/users/fetchReturnHearts.yaml
  /users/sendheartVirtual:
    $ref: paths/users/sendheartVirtual.yaml
  /users/sendheart:
    $ref: paths/users/sendheart.yaml
  /users/claimheart:
    $ref: paths/users/claimheart.yaml
  /users/verifyreturnhearts:
    $ref: paths/users/verifyreturnhearts.yaml
  /users/sentHeartDecoded:
    $ref: paths/users/sentHeartDecoded.yaml
  /users/special/returnclaimedheartlate:
    $ref: paths/users/special/returnclaimedheartlate.yaml
  /users/publish:
    $ref: paths/users/publish.yaml
  /users/mymatches:
    $ref: paths/users/mymatches.yaml